services:
  web:
    build: .
    container_name: mysupermarket_web
    restart: unless-stopped
    # El comando para arrancar Django
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    # Le decimos que tome TODO exclusivamente del .env
    env_file:
      - .env
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

volumes:
  media_volume:
  static_volume: