# Generated by Django 5.1.4 on 2026-03-24 04:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id_brand",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ["id_brand", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="super_brand_name_35b8ef_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id_category",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["id_category", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="super_categ_name_e1f197_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id_customer",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Apellido"
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Cédula"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Masculino"), (2, "Femenino")],
                        default=1,
                        null=True,
                        verbose_name="Genero",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Descuento (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["id_customer", "name", "last_name"],
                "indexes": [
                    models.Index(fields=["name"], name="super_custo_name_f529e4_idx"),
                    models.Index(
                        fields=["last_name"], name="super_custo_last_na_a6bce0_idx"
                    ),
                    models.Index(fields=["dni"], name="super_custo_dni_021113_idx"),
                    models.Index(fields=["email"], name="super_custo_email_9c637a_idx"),
                    models.Index(
                        fields=["address"], name="super_custo_address_fbe225_idx"
                    ),
                    models.Index(fields=["phone"], name="super_custo_phone_c057a7_idx"),
                    models.Index(
                        fields=["birth_date"], name="super_custo_birth_d_490f1b_idx"
                    ),
                    models.Index(
                        fields=["gender"], name="super_custo_gender_cfab31_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id_payment_method",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de Pago",
                "verbose_name_plural": "Forma de Pagos",
                "ordering": ["id_payment_method", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="super_payme_name_cf7f7f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id_product",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Stock"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products",
                        verbose_name="Imágen",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Código de barras",
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Fecha de elaboración",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "state",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.brand",
                        verbose_name="Marca",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["id_product", "name"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Cantidad")),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de agregado"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="super.cart",
                        verbose_name="Carrito",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item del Carrito",
                "verbose_name_plural": "Items del Carrito",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id_sale",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Fecha y Hora de venta",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Monto Recibido",
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Cambio",
                    ),
                ),
                (
                    "card_number_masked",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Tarjeta Censurado",
                    ),
                ),
                (
                    "transfer_account_masked",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de Cuenta Censurado",
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID generado por el cliente al abrir el checkout. Garantiza que un checkout doble no crea dos ventas.",
                        null=True,
                        unique=True,
                        verbose_name="Clave de idempotencia",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.paymentmethod",
                        verbose_name="Forma de pago",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que compró",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["id_sale"],
            },
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id_detail",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="Cantidad"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super.sale",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalle de Ventas",
                "ordering": ["id_detail", "sale", "product"],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id_seller",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Apellido"
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Cédula"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Masculino"), (2, "Femenino")],
                        default=1,
                        null=True,
                        verbose_name="Genero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
                "ordering": ["id_seller", "name", "last_name"],
                "indexes": [
                    models.Index(fields=["name"], name="super_selle_name_58af6c_idx"),
                    models.Index(
                        fields=["last_name"], name="super_selle_last_na_9ac507_idx"
                    ),
                    models.Index(fields=["dni"], name="super_selle_dni_c0c41e_idx"),
                    models.Index(fields=["email"], name="super_selle_email_9eef58_idx"),
                    models.Index(
                        fields=["address"], name="super_selle_address_3ca8bf_idx"
                    ),
                    models.Index(fields=["phone"], name="super_selle_phone_f1443d_idx"),
                    models.Index(
                        fields=["birth_date"], name="super_selle_birth_d_0ca156_idx"
                    ),
                    models.Index(
                        fields=["gender"], name="super_selle_gender_f9a322_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="super.seller",
                verbose_name="Vendedor",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="super_produ_name_b1f376_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="super_produ_brand_i_1bd1f8_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="super_produ_categor_f5f19c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["description"], name="super_produ_descrip_d9e1be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock"], name="super_produ_stock_44a164_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="super_produ_barcode_a6b537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["production_date"], name="super_produ_product_44dd51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["expiration_date"], name="super_produ_expirat_610cbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["state"], name="super_produ_state_0f8941_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="product_stock_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="product_price_non_negative"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AddIndex(
            model_name="saledetail",
            index=models.Index(
                fields=["product"], name="super_saled_product_926f49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saledetail",
            index=models.Index(fields=["sale"], name="super_saled_sale_id_b20b70_idx"),
        ),
        migrations.AddConstraint(
            model_name="saledetail",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="saledetail_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledetail",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="saledetail_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="saledetail",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="saledetail_subtotal_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["sale_date"], name="super_sale_sale_da_86a5f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer"], name="super_sale_custome_5c1968_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["seller"], name="super_sale_seller__28230c_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["idempotency_key"], name="super_sale_idempot_5567ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="sale_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("iva__gte", 0)), name="sale_iva_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0)),
                name="sale_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="sale_total_non_negative"
            ),
        ),
    ]
