# Generated by Django 5.1.4 on 2026-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="discount_expiry",
            field=models.DateField(
                blank=True,
                help_text="Fecha límite hasta la que aplica el descuento. Vacío = sin vigencia (no aplica).",
                null=True,
                verbose_name="Vigencia del descuento",
            ),
        ),
    ]
