# Generated by Django 5.1.4 on 2026-08-04 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super", "0003_alter_product_brand_alter_product_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recency_days", models.IntegerField(default=0)),
                ("frequency_30d", models.IntegerField(default=0)),
                (
                    "avg_ticket",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("leal", "Leal"),
                            ("en_riesgo", "En riesgo"),
                            ("perdido", "Perdido"),
                            ("campeon", "Campeón"),
                        ],
                        default="nuevo",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="super.customer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["segment"], name="super_custo_segment_032436_idx"
                    )
                ],
            },
        ),
    ]
