# Generated by Django 5.1.4 on 2026-08-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super", "0005_repurchasepattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="repurchasepattern",
            name="last_notified",
            field=models.DateField(
                blank=True,
                help_text="Evita reenviar el mismo recordatorio todos los días.",
                null=True,
                verbose_name="Última notificación enviada",
            ),
        ),
    ]
