# Generated by Django 5.1.4 on 2026-08-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super", "0006_repurchasepattern_last_notified"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "co_occurrence_count",
                    models.IntegerField(verbose_name="Veces compradas juntas"),
                ),
                ("confidence", models.FloatField(verbose_name="Confianza (0-1)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities_from",
                        to="super.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities_to",
                        to="super.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Afinidad de Productos",
                "verbose_name_plural": "Afinidades de Productos",
                "ordering": ["-confidence"],
                "indexes": [
                    models.Index(
                        fields=["product_a", "-confidence"],
                        name="super_produ_product_32664e_idx",
                    )
                ],
                "unique_together": {("product_a", "product_b")},
            },
        ),
    ]
