# Generated by Django 5.1.4 on 2026-08-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super", "0007_productaffinity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Se llena automáticamente al crear el producto. Distinta de 'Fecha de elaboración'.",
                null=True,
                verbose_name="Fecha de registro en el sistema",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="super_produ_created_bd2f0e_idx"
            ),
        ),
    ]
